version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: text_analyzer
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    depends_on:
      - mysql
      - redis
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=text_analyzer
      - GOOGLE_CLIENT_ID=1080329866905-foujof5pv53secruebk0jqaq0stajdt5.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:3000/api/v1/auth/google/callback
      - SESSION_SECRET=mysecret
      - JWT_SECRET=myjwtsecret
      - JWT_EXPIRATION=1h
      - REDIS_CLIENT=redis://redis:6379
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app

volumes:
  mysql_data:
